export const USER_LOGIN = 'USER_LOGIN';
export const AUTH_TOKEN_LOGIN = 'AUTH_TOKEN_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

export const RESTAURANT_MENU_COLLECT = 'RESTAURANT_MENU_COLLECT';
